2022-03-30 16:32:41.188 | ERROR    | conf.logger:log_request_error:18 - uid: 1, requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/album/1', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "id": 1\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.album.album_views.AlbumHandler object at 0x7ff325b1d760>
             │       │    └ ['1']
             │       └ <views.album.album_views.AlbumHandler object at 0x7ff325b1d760>
             └ <bound method AlbumHandler.get of <views.album.album_views.AlbumHandler object at 0x7ff325b1d760>>

  File "/Users/qiangchen/Desktop/Labs/Sao/views/album/album_views.py", line 16, in get
    assert album, 'album 不存在: %r' % album_id
           │                        └ '1'
           └ None

AssertionError: album 不存在: '1'
2022-03-30 16:34:02.717 | ERROR    | conf.logger:log_request_error:18 - uid: 1, requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/album/1', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "id": 1\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.album.album_views.AlbumHandler object at 0x7fbe49200730>
             │       │    └ ['1']
             │       └ <views.album.album_views.AlbumHandler object at 0x7fbe49200730>
             └ <bound method AlbumHandler.get of <views.album.album_views.AlbumHandler object at 0x7fbe49200730>>

  File "/Users/qiangchen/Desktop/Labs/Sao/views/album/album_views.py", line 16, in get
    assert album, 'album 不存在: %r' % album_id
           │                        └ '1'
           └ None

AssertionError: album 不存在: '1'
2022-03-30 16:36:57.361 | ERROR    | conf.logger:log_request_error:18 - uid: 1, requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/album/2', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "id": 1\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.album.album_views.AlbumHandler object at 0x7fe08bb1c730>
             │       │    └ ['2']
             │       └ <views.album.album_views.AlbumHandler object at 0x7fe08bb1c730>
             └ <bound method AlbumHandler.get of <views.album.album_views.AlbumHandler object at 0x7fe08bb1c730>>

  File "/Users/qiangchen/Desktop/Labs/Sao/views/album/album_views.py", line 16, in get
    assert album, 'album 不存在: %r' % album_id
           │                        └ '2'
           └ None

AssertionError: album 不存在: '2'
2022-03-31 10:05:42.490 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/common/feedback', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.common.common_views.UploadHandler object at 0x7f9f293014c0>
             │       │    └ []
             │       └ <views.common.common_views.UploadHandler object at 0x7f9f293014c0>
             └ <bound method RequestHandler._unimplemented_method of <views.common.common_views.UploadHandler object at 0x7f9f293014c0>>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 264, in _unimplemented_method
    raise HTTPError(405)
          └ <class 'tornado.web.HTTPError'>

tornado.web.HTTPError: HTTP 405: Method Not Allowed
2022-03-31 10:05:58.042 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/common/feedback', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.common.common_views.UploadHandler object at 0x7f9f29301b80>
             │       │    └ []
             │       └ <views.common.common_views.UploadHandler object at 0x7f9f29301b80>
             └ <bound method RequestHandler._unimplemented_method of <views.common.common_views.UploadHandler object at 0x7f9f29301b80>>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 264, in _unimplemented_method
    raise HTTPError(405)
          └ <class 'tornado.web.HTTPError'>

tornado.web.HTTPError: HTTP 405: Method Not Allowed
2022-03-31 10:06:21.036 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/common/feedback', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.common.common_views.FeedbackHandler object at 0x7ff0b2b088b0>
             │       │    └ []
             │       └ <views.common.common_views.FeedbackHandler object at 0x7ff0b2b088b0>
             └ <bound method FeedbackHandler.get of <views.common.common_views.FeedbackHandler object at 0x7ff0b2b088b0>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/common/common_views.py", line 22, in get
    self.render('feedback.html')
    │    └ <function RequestHandler.render at 0x7ff0b0d8c700>
    └ <views.common.common_views.FeedbackHandler object at 0x7ff0b2b088b0>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 863, in render
    html = self.render_string(template_name, **kwargs)
           │    │             │                └ {}
           │    │             └ 'feedback.html'
           │    └ <function RequestHandler.render_string at 0x7ff0b0d8c9d0>
           └ <views.common.common_views.FeedbackHandler object at 0x7ff0b2b088b0>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1009, in render_string
    t = loader.load(template_name)
        │      │    └ 'feedback.html'
        │      └ <function BaseLoader.load at 0x7ff0b0d5ddc0>
        └ <tornado.template.Loader object at 0x7ff0b2b08a30>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/template.py", line 446, in load
    self.templates[name] = self._create_template(name)
    │    │         │       │    │                └ 'feedback.html'
    │    │         │       │    └ <function Loader._create_template at 0x7ff0b0d71040>
    │    │         │       └ <tornado.template.Loader object at 0x7ff0b2b08a30>
    │    │         └ 'feedback.html'
    │    └ {}
    └ <tornado.template.Loader object at 0x7ff0b2b08a30>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/template.py", line 478, in _create_template
    template = Template(f.read(), name=name, loader=self)
               │        │ │            │            └ <tornado.template.Loader object at 0x7ff0b2b08a30>
               │        │ │            └ 'feedback.html'
               │        │ └ <method 'read' of '_io.BufferedReader' objects>
               │        └ <_io.BufferedReader name='/Users/qiangchen/Desktop/sesame/sesame-backend/templates/feedback.html'>
               └ <class 'tornado.template.Template'>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/template.py", line 318, in __init__
    self.file = _File(self, _parse(reader, self))
    │           │     │     │      │       └ <tornado.template.Template object at 0x7ff0b2b08dc0>
    │           │     │     │      └ <tornado.template._TemplateReader object at 0x7ff0b2b08ee0>
    │           │     │     └ <function _parse at 0x7ff0b0d77d30>
    │           │     └ <tornado.template.Template object at 0x7ff0b2b08dc0>
    │           └ <class 'tornado.template._File'>
    └ <tornado.template.Template object at 0x7ff0b2b08dc0>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/template.py", line 1048, in _parse
    reader.raise_parse_error("unknown operator: %r" % operator)
    │      │                                          └ 'static_url("css/bootstrap.min.css")'
    │      └ <function _TemplateReader.raise_parse_error at 0x7ff0b0d77ca0>
    └ <tornado.template._TemplateReader object at 0x7ff0b2b08ee0>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/template.py", line 839, in raise_parse_error
    raise ParseError(msg, self.name, self.line)
          │          │    │    │     │    └ 6
          │          │    │    │     └ <tornado.template._TemplateReader object at 0x7ff0b2b08ee0>
          │          │    │    └ 'feedback.html'
          │          │    └ <tornado.template._TemplateReader object at 0x7ff0b2b08ee0>
          │          └ 'unknown operator: \'static_url("css/bootstrap.min.css")\''
          └ <class 'tornado.template.ParseError'>

tornado.template.ParseError: unknown operator: 'static_url("css/bootstrap.min.css")' at feedback.html:6
2022-03-31 10:06:21.056 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/common/feedback', ip: '127.0.0.1', author: None, query: '', body: '', time: 26ms
2022-03-31 10:24:41.592 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/common/feedback', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.common.common_views.FeedbackHandler object at 0x7f81fbb18a00>
             │       │    └ []
             │       └ <views.common.common_views.FeedbackHandler object at 0x7f81fbb18a00>
             └ <bound method FeedbackHandler.get of <views.common.common_views.FeedbackHandler object at 0x7f81fbb18a00>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/common/common_views.py", line 22, in get
    self.render('feedback.html')
    │    └ <function RequestHandler.render at 0x7f81f9d8c700>
    └ <views.common.common_views.FeedbackHandler object at 0x7f81fbb18a00>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 863, in render
    html = self.render_string(template_name, **kwargs)
           │    │             │                └ {}
           │    │             └ 'feedback.html'
           │    └ <function RequestHandler.render_string at 0x7f81f9d8c9d0>
           └ <views.common.common_views.FeedbackHandler object at 0x7f81fbb18a00>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1009, in render_string
    t = loader.load(template_name)
        │      │    └ 'feedback.html'
        │      └ <function BaseLoader.load at 0x7f81f9d5ddc0>
        └ <tornado.template.Loader object at 0x7f81fbb18a60>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/template.py", line 446, in load
    self.templates[name] = self._create_template(name)
    │    │         │       │    │                └ 'feedback.html'
    │    │         │       │    └ <function Loader._create_template at 0x7f81f9d71040>
    │    │         │       └ <tornado.template.Loader object at 0x7f81fbb18a60>
    │    │         └ 'feedback.html'
    │    └ {}
    └ <tornado.template.Loader object at 0x7f81fbb18a60>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/template.py", line 478, in _create_template
    template = Template(f.read(), name=name, loader=self)
               │        │ │            │            └ <tornado.template.Loader object at 0x7f81fbb18a60>
               │        │ │            └ 'feedback.html'
               │        │ └ <method 'read' of '_io.BufferedReader' objects>
               │        └ <_io.BufferedReader name='/Users/qiangchen/Desktop/sesame/sesame-backend/templates/feedback.html'>
               └ <class 'tornado.template.Template'>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/template.py", line 318, in __init__
    self.file = _File(self, _parse(reader, self))
    │           │     │     │      │       └ <tornado.template.Template object at 0x7f81fbb18df0>
    │           │     │     │      └ <tornado.template._TemplateReader object at 0x7f81fbb18f10>
    │           │     │     └ <function _parse at 0x7f81f9d77d30>
    │           │     └ <tornado.template.Template object at 0x7f81fbb18df0>
    │           └ <class 'tornado.template._File'>
    └ <tornado.template.Template object at 0x7f81fbb18df0>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/template.py", line 1018, in _parse
    block_body = _parse(reader, template, operator, operator)
                 │      │       │         │         └ 'for'
                 │      │       │         └ 'for'
                 │      │       └ <tornado.template.Template object at 0x7f81fbb18df0>
                 │      └ <tornado.template._TemplateReader object at 0x7f81fbb18f10>
                 └ <function _parse at 0x7f81f9d77d30>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/template.py", line 863, in _parse
    reader.raise_parse_error(
    │      └ <function _TemplateReader.raise_parse_error at 0x7f81f9d77ca0>
    └ <tornado.template._TemplateReader object at 0x7f81fbb18f10>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/template.py", line 839, in raise_parse_error
    raise ParseError(msg, self.name, self.line)
          │          │    │    │     │    └ 19
          │          │    │    │     └ <tornado.template._TemplateReader object at 0x7f81fbb18f10>
          │          │    │    └ 'feedback.html'
          │          │    └ <tornado.template._TemplateReader object at 0x7f81fbb18f10>
          │          └ 'Missing {% end %} block for for'
          └ <class 'tornado.template.ParseError'>

tornado.template.ParseError: Missing {% end %} block for for at feedback.html:19
2022-03-31 10:24:41.613 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/common/feedback', ip: '127.0.0.1', author: None, query: '', body: '', time: 31ms
2022-03-31 10:24:53.520 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/common/feedback', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.common.common_views.FeedbackHandler object at 0x7f81fbb3e430>
             │       │    └ []
             │       └ <views.common.common_views.FeedbackHandler object at 0x7f81fbb3e430>
             └ <bound method FeedbackHandler.get of <views.common.common_views.FeedbackHandler object at 0x7f81fbb3e430>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/common/common_views.py", line 22, in get
    self.render('feedback.html')
    │    └ <function RequestHandler.render at 0x7f81f9d8c700>
    └ <views.common.common_views.FeedbackHandler object at 0x7f81fbb3e430>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 863, in render
    html = self.render_string(template_name, **kwargs)
           │    │             │                └ {}
           │    │             └ 'feedback.html'
           │    └ <function RequestHandler.render_string at 0x7f81f9d8c9d0>
           └ <views.common.common_views.FeedbackHandler object at 0x7f81fbb3e430>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1012, in render_string
    return t.generate(**namespace)
           │ │          └ {'handler': <views.common.common_views.FeedbackHandler object at 0x7f81fbb3e430>, 'request': HTTPServerRequest(protocol='http...
           │ └ <function Template.generate at 0x7f81f9d5da60>
           └ <tornado.template.Template object at 0x7f81fbb18940>
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/template.py", line 362, in generate
    return execute()
           └ <function _tt_execute at 0x7f81fbbef4c0>

  File "feedback_html.generated.py", line 11, in _tt_execute
    for category in categorys:  # feedback.html:11

NameError: name 'categorys' is not defined
2022-03-31 10:24:53.528 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/common/feedback', ip: '127.0.0.1', author: None, query: '', body: '', time: 19ms
2022-03-31 15:25:53.530 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/common/feedback', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
                   └ '/Users/qiangchen/Desktop/sesame/sesame-backend'

TypeError: object str can't be used in 'await' expression
2022-03-31 15:25:53.549 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/common/feedback', ip: '127.0.0.1', author: None, query: '', body: '', time: 27ms
2022-03-31 15:26:45.700 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/common/feedback', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
                   └ '/Users/qiangchen/Desktop/sesame/sesame-backend'

TypeError: object str can't be used in 'await' expression
2022-03-31 15:26:45.703 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/common/feedback', ip: '127.0.0.1', author: None, query: '', body: '', time:  4ms
2022-03-31 15:26:46.941 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/common/feedback', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
                   └ '/Users/qiangchen/Desktop/sesame/sesame-backend'

TypeError: object str can't be used in 'await' expression
2022-03-31 15:26:46.944 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/common/feedback', ip: '127.0.0.1', author: None, query: '', body: '', time:  4ms
2022-03-31 15:27:17.073 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/common/feedback', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
                   └ '/Users/qiangchen/Desktop/sesame/sesame-backend'

TypeError: object str can't be used in 'await' expression
2022-03-31 15:27:17.083 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/common/feedback', ip: '127.0.0.1', author: None, query: '', body: '', time: 13ms
2022-03-31 15:59:34.057 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7f82ae4ae340>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7f82ae4ae340>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7f82ae4ae340>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 16, in get
    with open(image_path, 'r') as f:
              └ '/Users/qiangchen/Desktop/sesame/sesame-backend/static/psq-consult-bg.png'

FileNotFoundError: [Errno 2] No such file or directory: '/Users/qiangchen/Desktop/sesame/sesame-backend/static/psq-consult-bg.png'
2022-03-31 15:59:34.072 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png', ip: '127.0.0.1', author: None, query: '', body: '', time: 19ms
2022-03-31 16:00:14.273 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7fa3f2b6e400>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7fa3f2b6e400>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7fa3f2b6e400>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 16, in get
    with open(image_path, 'r') as f:
              └ "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"

FileNotFoundError: [Errno 2] No such file or directory: "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"
2022-03-31 16:00:14.287 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png', ip: '127.0.0.1', author: None, query: '', body: '', time: 19ms
2022-03-31 16:01:17.993 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7fcc4ea5e3d0>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7fcc4ea5e3d0>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7fcc4ea5e3d0>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 17, in get
    with open(image_path, 'r') as f:
              └ "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"

FileNotFoundError: [Errno 2] No such file or directory: "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"
2022-03-31 16:01:18.007 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png', ip: '127.0.0.1', author: None, query: '', body: '', time: 18ms
2022-03-31 16:01:19.518 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7fcc4ea5e8e0>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7fcc4ea5e8e0>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7fcc4ea5e8e0>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 17, in get
    with open(image_path, 'r') as f:
              └ "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"

FileNotFoundError: [Errno 2] No such file or directory: "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"
2022-03-31 16:01:19.522 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png', ip: '127.0.0.1', author: None, query: '', body: '', time:  5ms
2022-03-31 16:01:53.510 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7ff1b4a71400>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7ff1b4a71400>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7ff1b4a71400>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 18, in get
    with open(image_path, 'r') as f:
              └ "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"

FileNotFoundError: [Errno 2] No such file or directory: "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"
2022-03-31 16:01:53.521 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png', ip: '127.0.0.1', author: None, query: '', body: '', time: 14ms
2022-03-31 16:03:06.274 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7f9a56a63400>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7f9a56a63400>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7f9a56a63400>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 18, in get
    with open(image_path, 'r') as f:
              └ "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"

FileNotFoundError: [Errno 2] No such file or directory: "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"
2022-03-31 16:03:06.288 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png', ip: '127.0.0.1', author: None, query: '', body: '', time: 17ms
2022-03-31 16:03:07.846 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7f9a56a63910>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7f9a56a63910>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7f9a56a63910>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 18, in get
    with open(image_path, 'r') as f:
              └ "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"

FileNotFoundError: [Errno 2] No such file or directory: "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"
2022-03-31 16:03:07.851 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png', ip: '127.0.0.1', author: None, query: '', body: '', time:  5ms
2022-03-31 16:03:43.556 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7f804536e400>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7f804536e400>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7f804536e400>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 18, in get
    with open(image_path, 'r') as f:
              └ "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"

FileNotFoundError: [Errno 2] No such file or directory: "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"
2022-03-31 16:03:43.568 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png', ip: '127.0.0.1', author: None, query: '', body: '', time: 16ms
2022-03-31 16:04:05.762 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7fe614c6e400>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7fe614c6e400>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7fe614c6e400>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 18, in get
    with open(image_path, 'r') as f:
              └ "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"

FileNotFoundError: [Errno 2] No such file or directory: "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"
2022-03-31 16:04:05.773 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png', ip: '127.0.0.1', author: None, query: '', body: '', time: 14ms
2022-03-31 16:04:27.173 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7fb520b71400>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7fb520b71400>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7fb520b71400>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 18, in get
    with open(image_path, 'r') as f:
              └ "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"

FileNotFoundError: [Errno 2] No such file or directory: "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"
2022-03-31 16:04:27.183 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png', ip: '127.0.0.1', author: None, query: '', body: '', time: 13ms
2022-03-31 16:04:28.130 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7fb520b71910>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7fb520b71910>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7fb520b71910>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 18, in get
    with open(image_path, 'r') as f:
              └ "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"

FileNotFoundError: [Errno 2] No such file or directory: "/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/'psq-consult-bg.png'"
2022-03-31 16:04:28.134 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png', ip: '127.0.0.1', author: None, query: '', body: '', time:  4ms
2022-03-31 16:04:49.060 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7f9705a71400>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7f9705a71400>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7f9705a71400>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 19, in get
    self.finish(f.read())
    │    │      │ └ <method 'read' of '_io.TextIOWrapper' objects>
    │    │      └ <_io.TextIOWrapper name='/Users/qiangchen/Desktop/sesame/sesame-backend/static/upload/psq-consult-bg.png' mode='r' encoding='...
    │    └ <function RequestHandler.finish at 0x7f970458cb80>
    └ <views.pic.pic_views.PicHandler object at 0x7f9705a71400>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
                         │    │              │     │    │       └ True
                         │    │              │     │    └ 'strict'
                         │    │              │     └ <encodings.utf_8.IncrementalDecoder object at 0x7f9705a71460>
                         │    │              └ b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x04\x0b\x00\x00\x01,\x08\x06\x00\x00\x00\xa5\xab:\x9e\x00\x00\x00\x01sRGB\x00\x...
                         │    └ <built-in function utf_8_decode>
                         └ <encodings.utf_8.IncrementalDecoder object at 0x7f9705a71460>

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
2022-03-31 16:04:49.074 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png', ip: '127.0.0.1', author: None, query: '', body: '', time: 19ms
2022-03-31 16:16:33.112 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png?width=100&height=50', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'width=100&height=50', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7fe05eb6e820>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7fe05eb6e820>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7fe05eb6e820>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 33, in get
    print("缩略图: %s %s" % width, height)
                         │      └ '50'
                         └ '100'

TypeError: not enough arguments for format string
2022-03-31 16:16:33.122 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png?width=100&height=50', ip: '127.0.0.1', author: None, query: 'width=100&height=50', body: '', time: 72ms
2022-03-31 16:16:58.565 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png?width=100&height=50', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'width=100&height=50', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7f87b1a71400>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7f87b1a71400>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7f87b1a71400>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 34, in get
    copy.thumbnail(size)
    │    │         └ ('100', '50')
    │    └ <function Image.thumbnail at 0x7f87b1a3af70>
    └ <PIL.Image.Image image mode=RGBA size=1035x300 at 0x7F87B1A71460>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/PIL/Image.py", line 2353, in thumbnail
    x, y = map(math.floor, size)
               │    │      └ ('100', '50')
               │    └ <built-in function floor>
               └ <module 'math' from '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/math.cpython-39-darwin.so'>

TypeError: must be real number, not str
2022-03-31 16:16:58.574 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png?width=100&height=50', ip: '127.0.0.1', author: None, query: 'width=100&height=50', body: '', time: 61ms
2022-03-31 16:18:15.416 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png?width=500&height=200', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'width=500&height=200', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7fcdf2381400>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7fcdf2381400>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7fcdf2381400>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 33, in get
    print("缩略图: %r" % size)
                      └ (500, 200)

TypeError: not all arguments converted during string formatting
2022-03-31 16:18:15.425 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png?width=500&height=200', ip: '127.0.0.1', author: None, query: 'width=500&height=200', body: '', time: 48ms
2022-03-31 16:31:57.250 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png?width=500&height=200', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'width=500&height=200', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/PIL/Image.py", line 2192, in save
    format = EXTENSION[ext]
             │         └ ''
             └ {'.bmp': 'BMP', '.dib': 'DIB', '.gif': 'GIF', '.tif': 'TIFF', '.tiff': 'TIFF', '.jfif': 'JPEG', '.jpe': 'JPEG', '.jpg': 'JPEG...

KeyError: ''


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7f8c322633a0>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7f8c322633a0>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7f8c322633a0>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 34, in get
    copy.save(tempIO)
    │    │    └ <_io.BytesIO object at 0x7f8c322fcea0>
    │    └ <function Image.save at 0x7f8c3222bc10>
    └ <PIL.Image.Image image mode=RGBA size=500x145 at 0x7F8C32263400>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/PIL/Image.py", line 2194, in save
    raise ValueError(f"unknown file extension: {ext}") from e

ValueError: unknown file extension: 
2022-03-31 16:31:57.261 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png?width=500&height=200', ip: '127.0.0.1', author: None, query: 'width=500&height=200', body: '', time: 113ms
2022-03-31 16:34:18.408 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png?width=500&height=200', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'width=500&height=200', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7f872ab803d0>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7f872ab803d0>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7f872ab803d0>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 34, in get
    copy.save(tempIO, format=path.splitext(image_name)[1])
    │    │    │              │    │        └ 'upload/psq-consult-bg.png'
    │    │    │              │    └ <function splitext at 0x7f8724f8cca0>
    │    │    │              └ <module 'posixpath' from '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py'>
    │    │    └ <_io.BytesIO object at 0x7f87289611d0>
    │    └ <function Image.save at 0x7f872ab48c10>
    └ <PIL.Image.Image image mode=RGBA size=500x145 at 0x7F872AB80430>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/PIL/Image.py", line 2201, in save
    save_handler = SAVE[format.upper()]
                   │    │      └ <method 'upper' of 'str' objects>
                   │    └ '.png'
                   └ {'BMP': <function _save at 0x7f872abb4700>, 'DIB': <function _dib_save at 0x7f872abb44c0>, 'GIF': <function _save at 0x7f872a...

KeyError: '.PNG'
2022-03-31 16:34:18.419 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png?width=500&height=200', ip: '127.0.0.1', author: None, query: 'width=500&height=200', body: '', time: 95ms
2022-03-31 16:38:54.446 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/pic/psq-consult-bg.png?width=500&height=200', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'width=500&height=200', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.pic.pic_views.PicHandler object at 0x7f9cbba71400>
             │       │    └ ['psq-consult-bg.png']
             │       └ <views.pic.pic_views.PicHandler object at 0x7f9cbba71400>
             └ <bound method PicHandler.get of <views.pic.pic_views.PicHandler object at 0x7f9cbba71400>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/pic/pic_views.py", line 39, in get
    copy.save(tempIO, format=[1])
    │    │    └ <_io.BytesIO object at 0x7f9cbbc48f40>
    │    └ <function Image.save at 0x7f9cbba39ca0>
    └ <PIL.Image.Image image mode=RGBA size=500x145 at 0x7F9CBBA71460>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/PIL/Image.py", line 2196, in save
    if format.upper() not in SAVE:
       │                     └ {'BMP': <function _save at 0x7f9cbbaa5790>, 'DIB': <function _dib_save at 0x7f9cbbaa5550>, 'GIF': <function _save at 0x7f9cbb...
       └ [1]

AttributeError: 'list' object has no attribute 'upper'
2022-03-31 16:38:54.457 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/pic/psq-consult-bg.png?width=500&height=200', ip: '127.0.0.1', author: None, query: 'width=500&height=200', body: '', time: 64ms
2022-04-01 13:23:43.879 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "code": "123456"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7fdc32cb4670>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7fdc32cb4670>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7fdc32cb4670>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 40, in post
    self._login_with_code(phone, code)
    │    │                │      └ '123456'
    │    │                └ '18856931381'
    │    └ <function LoginHandler._login_with_code at 0x7fdc32ae2700>
    └ <views.login.login_views.LoginHandler object at 0x7fdc32cb4670>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 68, in _login_with_code
    self._login_success(user)
    │    │              └ <models.user_model.User object at 0x7fdc32d48070>
    │    └ <function LoginHandler._login_success at 0x7fdc32ae2790>
    └ <views.login.login_views.LoginHandler object at 0x7fdc32cb4670>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 77, in _login_success
    token = common.jwt_utils.JWTUtils.create(user.id)
            │      │         │        │      │    └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7fdc32a97770>
            │      │         │        │      └ <models.user_model.User object at 0x7fdc32d48070>
            │      │         │        └ <classmethod object at 0x7fdc32abc520>
            │      │         └ <class 'common.jwt_utils.JWTUtils'>
            │      └ <module 'common.jwt_utils' from '/Users/qiangchen/Desktop/sesame/sesame-backend/common/jwt_utils.py'>
            └ <module 'common' (namespace)>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/common/jwt_utils.py", line 15, in create
    encoded = jwt.encode(payload, JWTUtils.SECRET, algorithm='HS256')
              │          │        │        └ 'SAO-Sao_sao'
              │          │        └ <class 'common.jwt_utils.JWTUtils'>
              │          └ {'uid': 1, 'exp': 1648877023}
              └ <module 'jwt' from '/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/jwt/__init__.py'>

AttributeError: module 'jwt' has no attribute 'encode'
2022-04-01 13:23:43.891 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "code": "123456"\n}', time: 142ms
2022-04-01 13:39:34.939 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "code": "bei1202jing"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7f9cded05040>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7f9cded05040>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7f9cded05040>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 40, in post
    self._login_with_code(phone, code)
    │    │                │      └ 'bei1202jing'
    │    │                └ '18856931381'
    │    └ <function LoginHandler._login_with_code at 0x7f9cdec44c10>
    └ <views.login.login_views.LoginHandler object at 0x7f9cded05040>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 66, in _login_with_code
    if not check_code(code): raise ClientError('验证码错误')
           │          │            └ <function ClientError at 0x7f9cdec41e50>
           │          └ 'bei1202jing'
           └ <function check_code at 0x7f9cdeb71160>

common.exception.SaoException: ('验证码错误', 1007)
2022-04-01 13:39:34.963 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "code": "bei1202jing"\n}', time: 44ms
2022-04-01 13:39:42.941 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7f9cded05070>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7f9cded05070>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7f9cded05070>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 38, in post
    self._login_with_password(phone, password)  # 密码登录
    │    │                    │      └ 'bei1202jing'
    │    │                    └ '18856931381'
    │    └ <function LoginHandler._login_with_password at 0x7f9cdec44b80>
    └ <views.login.login_views.LoginHandler object at 0x7f9cded05070>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 51, in _login_with_password
    is_valid, msg = validate_password(password)
                    │                 └ 'bei1202jing'
                    └ <function validate_password at 0x7f9cdec445e0>

TypeError: validate_password() missing 1 required positional argument: 'password'
2022-04-01 13:39:42.960 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}', time: 19ms
2022-04-01 13:40:56.720 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7ff93c507070>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7ff93c507070>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7ff93c507070>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 38, in post
    self._login_with_password(phone, password)  # 密码登录
    │    │                    │      └ 'bei1202jing'
    │    │                    └ '18856931381'
    │    └ <function LoginHandler._login_with_password at 0x7ff93c43bb80>
    └ <views.login.login_views.LoginHandler object at 0x7ff93c507070>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 52, in _login_with_password
    if not is_valid: raise ClientError(msg)
           │               │           └ '密码错误: 必须包含数字'
           │               └ <function ClientError at 0x7ff93c447e50>
           └ False

common.exception.SaoException: ('密码错误: 必须包含数字', 1007)
2022-04-01 13:40:56.748 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}', time: 45ms
2022-04-01 13:42:02.001 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7fe91cbd3cd0>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7fe91cbd3cd0>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7fe91cbd3cd0>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 38, in post
    self._login_with_password(phone, password)  # 密码登录
    │    │                    │      └ 'bei1202jing'
    │    │                    └ '18856931381'
    │    └ <function LoginHandler._login_with_password at 0x7fe91cb2ab80>
    └ <views.login.login_views.LoginHandler object at 0x7fe91cbd3cd0>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 52, in _login_with_password
    if not is_valid: raise ClientError(msg)
           │               │           └ '密码错误: 必须包含数字'
           │               └ <function ClientError at 0x7fe91cb30e50>
           └ False

common.exception.SaoException: ('密码错误: 必须包含数字', 1007)
2022-04-01 13:42:02.043 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}', time: 59ms
2022-04-01 13:43:01.892 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7fabef644070>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7fabef644070>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7fabef644070>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 38, in post
    self._login_with_password(phone, password)  # 密码登录
    │    │                    │      └ 'bei1202jing'
    │    │                    └ '18856931381'
    │    └ <function LoginHandler._login_with_password at 0x7fabef57bb80>
    └ <views.login.login_views.LoginHandler object at 0x7fabef644070>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 52, in _login_with_password
    if not is_valid: raise ClientError(msg)
           │               │           └ '密码错误: 必须包含数字'
           │               └ <function ClientError at 0x7fabef580e50>
           └ False

common.exception.SaoException: ('密码错误: 必须包含数字', 1007)
2022-04-01 13:43:01.936 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}', time: 66ms
2022-04-01 13:43:23.616 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7ffd3c644070>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7ffd3c644070>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7ffd3c644070>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 38, in post
    self._login_with_password(phone, password)  # 密码登录
    │    │                    │      └ 'bei1202jing'
    │    │                    └ '18856931381'
    │    └ <function LoginHandler._login_with_password at 0x7ffd3c43fb80>
    └ <views.login.login_views.LoginHandler object at 0x7ffd3c644070>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 52, in _login_with_password
    if not is_valid: raise ClientError(msg)
           │               │           └ '密码错误: 必须包含数字'
           │               └ <function ClientError at 0x7ffd3c444e50>
           └ False

common.exception.SaoException: ('密码错误: 必须包含数字', 1007)
2022-04-01 13:43:23.637 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}', time: 37ms
2022-04-01 13:48:35.649 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7ffced502070>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7ffced502070>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7ffced502070>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 38, in post
    self._login_with_password(phone, password)  # 密码登录
    │    │                    │      └ 'bei1202jing'
    │    │                    └ '18856931381'
    │    └ <function LoginHandler._login_with_password at 0x7ffced439b80>
    └ <views.login.login_views.LoginHandler object at 0x7ffced502070>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 52, in _login_with_password
    if not is_valid: raise ClientError(msg)
           │               │           └ '密码错误: 必须包含数字'
           │               └ <function ClientError at 0x7ffced43ee50>
           └ False

common.exception.SaoException: ('密码错误: 必须包含数字', 1007)
2022-04-01 13:48:35.673 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}', time: 40ms
2022-04-01 13:48:57.112 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7ffced5020a0>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7ffced5020a0>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7ffced5020a0>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 38, in post
    self._login_with_password(phone, password)  # 密码登录
    │    │                    │      └ 'bei1202jing'
    │    │                    └ '18856931381'
    │    └ <function LoginHandler._login_with_password at 0x7ffced439b80>
    └ <views.login.login_views.LoginHandler object at 0x7ffced5020a0>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 52, in _login_with_password
    if not is_valid: raise ClientError(msg)
           │               │           └ '密码错误: 必须包含数字'
           │               └ <function ClientError at 0x7ffced43ee50>
           └ False

common.exception.SaoException: ('密码错误: 必须包含数字', 1007)
2022-04-01 13:48:57.126 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}', time: 15ms
2022-04-01 13:49:16.012 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7f99c6d04040>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7f99c6d04040>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7f99c6d04040>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 38, in post
    self._login_with_password(phone, password)  # 密码登录
    │    │                    │      └ 'bei1202jing'
    │    │                    └ '18856931381'
    │    └ <function LoginHandler._login_with_password at 0x7f99c6c3bb80>
    └ <views.login.login_views.LoginHandler object at 0x7f99c6d04040>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 52, in _login_with_password
    if not is_valid: raise ClientError(msg)
           │               │           └ '密码错误: 必须包含数字'
           │               └ <function ClientError at 0x7f99c6c40e50>
           └ False

common.exception.SaoException: ('密码错误: 必须包含数字', 1007)
2022-04-01 13:49:16.054 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}', time: 64ms
2022-04-01 13:52:05.867 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7fc26cbe1cd0>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7fc26cbe1cd0>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7fc26cbe1cd0>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 38, in post
    self._login_with_password(phone, password)  # 密码登录
    │    │                    │      └ 'bei1202jing'
    │    │                    └ '18856931381'
    │    └ <function LoginHandler._login_with_password at 0x7fc26cb38b80>
    └ <views.login.login_views.LoginHandler object at 0x7fc26cbe1cd0>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 52, in _login_with_password
    if not is_valid: raise ClientError(msg)
           │               │           └ '密码错误: 仅能使用英文字母, 数字和下划线'
           │               └ <function ClientError at 0x7fc26cb3ee50>
           └ False

common.exception.SaoException: ('密码错误: 仅能使用英文字母, 数字和下划线', 1007)
2022-04-01 13:52:05.892 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}', time: 39ms
2022-04-01 13:52:22.786 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7ffbd7d05040>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7ffbd7d05040>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7ffbd7d05040>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 38, in post
    self._login_with_password(phone, password)  # 密码登录
    │    │                    │      └ 'bei1202jing'
    │    │                    └ '18856931381'
    │    └ <function LoginHandler._login_with_password at 0x7ffbd7c42b80>
    └ <views.login.login_views.LoginHandler object at 0x7ffbd7d05040>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 52, in _login_with_password
    if not is_valid: raise ClientError(msg)
           │               │           └ '密码错误: 仅能使用英文字母, 数字和下划线'
           │               └ <function ClientError at 0x7ffbd7c41e50>
           └ False

common.exception.SaoException: ('密码错误: 仅能使用英文字母, 数字和下划线', 1007)
2022-04-01 13:52:22.834 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}', time: 65ms
2022-04-01 13:52:48.563 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7faf813e1ee0>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7faf813e1ee0>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7faf813e1ee0>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 38, in post
    self._login_with_password(phone, password)  # 密码登录
    │    │                    │      └ 'bei1202jing'
    │    │                    └ '18856931381'
    │    └ <function LoginHandler._login_with_password at 0x7faf8133fb80>
    └ <views.login.login_views.LoginHandler object at 0x7faf813e1ee0>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 52, in _login_with_password
    if not is_valid: raise ClientError(msg)
           │               │           └ '密码错误: 仅能使用英文字母, 数字和下划线'
           │               └ <function ClientError at 0x7faf8133ee50>
           └ False

common.exception.SaoException: ('密码错误: 仅能使用英文字母, 数字和下划线', 1007)
2022-04-01 13:52:48.624 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}', time: 71ms
2022-04-01 13:52:55.771 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7f96273fe040>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7f96273fe040>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7f96273fe040>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 38, in post
    self._login_with_password(phone, password)  # 密码登录
    │    │                    │      └ 'bei1202jing'
    │    │                    └ '18856931381'
    │    └ <function LoginHandler._login_with_password at 0x7f9627338b80>
    └ <views.login.login_views.LoginHandler object at 0x7f96273fe040>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 52, in _login_with_password
    if not is_valid: raise ClientError(msg)
           │               │           └ '密码错误: 仅能使用英文字母, 数字和下划线'
           │               └ <function ClientError at 0x7f962733ee50>
           └ False

common.exception.SaoException: ('密码错误: 仅能使用英文字母, 数字和下划线', 1007)
2022-04-01 13:52:55.794 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}', time: 37ms
2022-04-01 13:52:58.768 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7f96273fe070>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7f96273fe070>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7f96273fe070>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 38, in post
    self._login_with_password(phone, password)  # 密码登录
    │    │                    │      └ 'bei1202jing'
    │    │                    └ '18856931381'
    │    └ <function LoginHandler._login_with_password at 0x7f9627338b80>
    └ <views.login.login_views.LoginHandler object at 0x7f96273fe070>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 52, in _login_with_password
    if not is_valid: raise ClientError(msg)
           │               │           └ '密码错误: 仅能使用英文字母, 数字和下划线'
           │               └ <function ClientError at 0x7f962733ee50>
           └ False

common.exception.SaoException: ('密码错误: 仅能使用英文字母, 数字和下划线', 1007)
2022-04-01 13:52:58.787 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}', time: 20ms
2022-04-01 13:53:12.225 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7ffe28cf9070>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7ffe28cf9070>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7ffe28cf9070>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 38, in post
    self._login_with_password(phone, password)  # 密码登录
    │    │                    │      └ 'bei1202jing'
    │    │                    └ '18856931381'
    │    └ <function LoginHandler._login_with_password at 0x7ffe28c2fb80>
    └ <views.login.login_views.LoginHandler object at 0x7ffe28cf9070>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 56, in _login_with_password
    if not validate_password(user.password, password): raise ClientError('密码错误')
           │                 │    │         │                └ <function ClientError at 0x7ffe28c35e50>
           │                 │    │         └ 'bei1202jing'
           │                 │    └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7ffe28b8cae0>
           │                 └ <models.user_model.User object at 0x7ffe28d72fa0>
           └ <function validate_password at 0x7ffe28c2f5e0>

common.exception.SaoException: ('密码错误', 1007)
2022-04-01 13:53:12.239 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "password": "bei1202jing"\n}', time: 93ms
2022-04-01 13:53:41.319 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "password": "chenzhinma"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7ffe28cf9190>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7ffe28cf9190>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7ffe28cf9190>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 38, in post
    self._login_with_password(phone, password)  # 密码登录
    │    │                    │      └ 'chenzhinma'
    │    │                    └ '18856931381'
    │    └ <function LoginHandler._login_with_password at 0x7ffe28c2fb80>
    └ <views.login.login_views.LoginHandler object at 0x7ffe28cf9190>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/login/login_views.py", line 52, in _login_with_password
    if not is_valid: raise ClientError(msg)
           │               │           └ '密码错误: 必须包含数字'
           │               └ <function ClientError at 0x7ffe28c35e50>
           └ False

common.exception.SaoException: ('密码错误: 必须包含数字', 1007)
2022-04-01 13:53:41.335 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/login/', ip: '127.0.0.1', author: None, query: '', body: '{\n    "phone": "18856931381",\n    "password": "chenzhinma"\n}', time: 17ms
2022-04-01 16:00:33.871 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/user/1', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "nickname": "\xe9\x99\x88\xe8\x8a\x9d\xe9\xba\xbb"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1681, in _execute
    result = self.prepare()
             │    └ <function UserHandler.prepare at 0x7f8a1cc3bee0>
             └ <views.users.user_views.UserHandler object at 0x7f8a1cd03040>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/users/user_views.py", line 17, in prepare
    if self.user and not self.user.deleted: raise ClientError('用户不存在, uid: %r' % uid)
       │    │            │    │    │              │                              └ '1'
       │    │            │    │    │              └ <function ClientError at 0x7f8a1cc40e50>
       │    │            │    │    └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7f8a1ca95c70>
       │    │            │    └ <models.user_model.User object at 0x7f8a1cd7ed00>
       │    │            └ <views.users.user_views.UserHandler object at 0x7f8a1cd03040>
       │    └ <models.user_model.User object at 0x7f8a1cd7ed00>
       └ <views.users.user_views.UserHandler object at 0x7f8a1cd03040>

common.exception.SaoException: ("用户不存在, uid: '1'", 1007)
2022-04-01 16:00:33.889 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/user/1', ip: '127.0.0.1', author: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsImV4cCI6MTY0ODg3ODg0NH0.mbEedLMYH2S1uk63LIdUcqIW5Rj5gdgeiVYB8lcG1qg', query: '', body: '{\n    "nickname": "陈芝麻"\n}', time: 247ms
2022-04-01 16:21:23.410 | ERROR    | conf.logger:log_request_error:18 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/user/1', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'----------------------------421993960879986741439976\r\nContent-Disposition: form-data; name="nickname"\r\n\r\n\xe9\x99\x88\xe8\x8a\x9d\xe9\xba\xbb\r\n----------------------------421993960879986741439976--\r\n'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1681, in _execute
    result = self.prepare()
             │    └ <function UserHandler.prepare at 0x7fe667d7aee0>
             └ <views.users.user_views.UserHandler object at 0x7fe667e23f40>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/users/user_views.py", line 18, in prepare
    super(AuthBaseHandler, self).prepare()
          │                └ <views.users.user_views.UserHandler object at 0x7fe667e23f40>
          └ <class 'views.base.base_views.AuthBaseHandler'>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/base/base_views.py", line 20, in prepare
    assert self.request.headers.get('Content-Type', '').startswith('application/json'), \
           │    │       │       └ <function Mapping.get at 0x7fe66418b8b0>
           │    │       └ <tornado.httputil.HTTPHeaders object at 0x7fe667e12730>
           │    └ HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/user/1', version='HTTP/1.1', remote_ip='127...
           └ <views.users.user_views.UserHandler object at 0x7fe667e23f40>

AssertionError: Content-Type 设置错误
2022-04-01 16:21:23.449 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'POST', uri: '/v1/user/1', ip: '127.0.0.1', author: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsImV4cCI6MTY0ODg3ODg0NH0.mbEedLMYH2S1uk63LIdUcqIW5Rj5gdgeiVYB8lcG1qg', query: '', body: '----------------------------421993960879986741439976\r\nContent-Disposition: form-data; name="nickname"\r\n\r\n陈芝麻\r\n----------------------------421993960879986741439976--\r\n', time: 47ms
2022-04-01 17:54:14.580 | ERROR    | conf.logger:log_request_error:18 - uid: 1, requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/album/1/photo?page=0&user_id=2', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'page=0&user_id=2', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.album.photo_views.PhotoHandler object at 0x7fddf8ce3fa0>
             │       │    └ ['1', None]
             │       └ <views.album.photo_views.PhotoHandler object at 0x7fddf8ce3fa0>
             └ <bound method PhotoHandler.get of <views.album.photo_views.PhotoHandler object at 0x7fddf8ce3fa0>>

TypeError: get() takes 2 positional arguments but 3 were given
2022-04-01 17:54:14.615 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/album/1/photo?page=0&user_id=2', ip: '127.0.0.1', author: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsImV4cCI6MTY0ODg3ODg0NH0.mbEedLMYH2S1uk63LIdUcqIW5Rj5gdgeiVYB8lcG1qg', query: 'page=0&user_id=2', body: '', time: 90ms
2022-04-01 17:54:42.071 | ERROR    | conf.logger:log_request_error:18 - uid: 1, requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/album/1/photo?page=0&user_id=2', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'page=0&user_id=2', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 327, in __getattr__
    return getattr(self.comparator, key)
                   │    │           └ 'user_id'
                   │    └ <sqlalchemy.orm.relationships.RelationshipProperty.Comparator object at 0x7ff0b8b957c0>
                   └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7ff0b8b95810>

AttributeError: 'Comparator' object has no attribute 'user_id'


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.album.photo_views.PhotoHandler object at 0x7ff0b8d07040>
             │       │    └ ['1', None]
             │       └ <views.album.photo_views.PhotoHandler object at 0x7ff0b8d07040>
             └ <bound method PhotoHandler.get of <views.album.photo_views.PhotoHandler object at 0x7ff0b8d07040>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/album/photo_views.py", line 31, in get
    count, photos = paginate(self, Photo, Photo.album_id == album_id, Photo.album.user_id == user_id)
                    │        │     │      │     │           │         │     │                └ '2'
                    │        │     │      │     │           │         │     └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7ff0b8b95810>
                    │        │     │      │     │           │         └ <class 'models.album_model.Photo'>
                    │        │     │      │     │           └ '1'
                    │        │     │      │     └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7ff0b8b95c20>
                    │        │     │      └ <class 'models.album_model.Photo'>
                    │        │     └ <class 'models.album_model.Photo'>
                    │        └ <views.album.photo_views.PhotoHandler object at 0x7ff0b8d07040>
                    └ <function paginate at 0x7ff0b8c48790>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 329, in __getattr__
    util.raise_(
    │    └ <function raise_ at 0x7ff0b77403a0>
    └ <module 'sqlalchemy.util' from '/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/sqlalchemy/ut...
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception

AttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Photo.album has an attribute 'user_id'
2022-04-01 17:54:42.095 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/album/1/photo?page=0&user_id=2', ip: '127.0.0.1', author: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsImV4cCI6MTY0ODg3ODg0NH0.mbEedLMYH2S1uk63LIdUcqIW5Rj5gdgeiVYB8lcG1qg', query: 'page=0&user_id=2', body: '', time: 73ms
2022-04-01 17:54:55.596 | ERROR    | conf.logger:log_request_error:18 - uid: 1, requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/album/1/photo?page=0&user_id=2', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'page=0&user_id=2', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 327, in __getattr__
    return getattr(self.comparator, key)
                   │    │           └ 'user_id'
                   │    └ <sqlalchemy.orm.relationships.RelationshipProperty.Comparator object at 0x7fa860a7c860>
                   └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7fa860a7c8b0>

AttributeError: 'Comparator' object has no attribute 'user_id'


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.album.photo_views.PhotoHandler object at 0x7fa860bf3040>
             │       │    └ ['1', None]
             │       └ <views.album.photo_views.PhotoHandler object at 0x7fa860bf3040>
             └ <bound method PhotoHandler.get of <views.album.photo_views.PhotoHandler object at 0x7fa860bf3040>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/album/photo_views.py", line 31, in get
    count, photos = paginate(self, Photo, Photo.album_id == album_id, Photo.album.user_id == user_id)
                    │        │     │      │     │           │         │     │                └ '2'
                    │        │     │      │     │           │         │     └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7fa860a7c8b0>
                    │        │     │      │     │           │         └ <class 'models.album_model.Photo'>
                    │        │     │      │     │           └ '1'
                    │        │     │      │     └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7fa860a7ccc0>
                    │        │     │      └ <class 'models.album_model.Photo'>
                    │        │     └ <class 'models.album_model.Photo'>
                    │        └ <views.album.photo_views.PhotoHandler object at 0x7fa860bf3040>
                    └ <function paginate at 0x7fa860b34790>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 329, in __getattr__
    util.raise_(
    │    └ <function raise_ at 0x7fa85ff403a0>
    └ <module 'sqlalchemy.util' from '/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/sqlalchemy/ut...
  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception

AttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Photo.album has an attribute 'user_id'
2022-04-01 17:54:55.622 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/album/1/photo?page=0&user_id=2', ip: '127.0.0.1', author: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsImV4cCI6MTY0ODg3ODg0NH0.mbEedLMYH2S1uk63LIdUcqIW5Rj5gdgeiVYB8lcG1qg', query: 'page=0&user_id=2', body: '', time: 65ms
2022-04-01 18:01:10.109 | ERROR    | conf.logger:log_request_error:18 - uid: 1, requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/album/1/photo?page=0&user_id=2', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'page=0&user_id=2', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.album.photo_views.PhotoHandler object at 0x7f813be02040>
             │       │    └ ['1', None]
             │       └ <views.album.photo_views.PhotoHandler object at 0x7f813be02040>
             └ <bound method PhotoHandler.get of <views.album.photo_views.PhotoHandler object at 0x7f813be02040>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/album/photo_views.py", line 32, in get
    if not album: raise ClientError('相册不存在')
           │            └ <function ClientError at 0x7f813bd40e50>
           └ None

common.exception.SaoException: ('相册不存在', 1007)
2022-04-01 18:01:10.122 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/album/1/photo?page=0&user_id=2', ip: '127.0.0.1', author: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsImV4cCI6MTY0ODg3ODg0NH0.mbEedLMYH2S1uk63LIdUcqIW5Rj5gdgeiVYB8lcG1qg', query: 'page=0&user_id=2', body: '', time: 64ms
2022-04-01 18:15:54.074 | ERROR    | conf.logger:log_request_error:18 - uid: 1, requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/album/1/photo/1?user_id=1&', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'user_id=1&', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.album.photo_views.PhotoHandler object at 0x7f9789508040>
             │       │    └ ['1', '1']
             │       └ <views.album.photo_views.PhotoHandler object at 0x7f9789508040>
             └ <bound method PhotoHandler.get of <views.album.photo_views.PhotoHandler object at 0x7f9789508040>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/album/photo_views.py", line 40, in get
    self.success(photo.to_json())
    │    │       └ <sqlalchemy.orm.query.Query object at 0x7f978958dc40>
    │    └ <function BaseHandler.success at 0x7f978943b1f0>
    └ <views.album.photo_views.PhotoHandler object at 0x7f9789508040>

AttributeError: 'Query' object has no attribute 'to_json'
2022-04-01 18:15:54.094 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/album/1/photo/1?user_id=1&', ip: '127.0.0.1', author: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsImV4cCI6MTY0ODg3ODg0NH0.mbEedLMYH2S1uk63LIdUcqIW5Rj5gdgeiVYB8lcG1qg', query: 'user_id=1&', body: '', time: 101ms
2022-04-01 18:17:16.902 | ERROR    | conf.logger:log_request_error:18 - uid: 1, requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/album/1/photo/1?user_id=1&', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'user_id=1&', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.album.photo_views.PhotoHandler object at 0x7fd669d08040>
             │       │    └ ['1', '1']
             │       └ <views.album.photo_views.PhotoHandler object at 0x7fd669d08040>
             └ <bound method PhotoHandler.get of <views.album.photo_views.PhotoHandler object at 0x7fd669d08040>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/album/photo_views.py", line 40, in get
    if not photo: raise ClientError('图片不存在')
           │            └ <function ClientError at 0x7fd669c41e50>
           └ None

common.exception.SaoException: ('图片不存在', 1007)
2022-04-01 18:17:16.918 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/album/1/photo/1?user_id=1&', ip: '127.0.0.1', author: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsImV4cCI6MTY0ODg3ODg0NH0.mbEedLMYH2S1uk63LIdUcqIW5Rj5gdgeiVYB8lcG1qg', query: 'user_id=1&', body: '', time: 83ms
2022-04-01 18:17:42.645 | ERROR    | conf.logger:log_request_error:18 - uid: 1, requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/album/1/photo/1?photo_id=2&user_id=1', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'photo_id=2&user_id=1', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.album.photo_views.PhotoHandler object at 0x7fd669ce5eb0>
             │       │    └ ['1', '1']
             │       └ <views.album.photo_views.PhotoHandler object at 0x7fd669ce5eb0>
             └ <bound method PhotoHandler.get of <views.album.photo_views.PhotoHandler object at 0x7fd669ce5eb0>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/album/photo_views.py", line 40, in get
    if not photo: raise ClientError('图片不存在')
           │            └ <function ClientError at 0x7fd669c41e50>
           └ None

common.exception.SaoException: ('图片不存在', 1007)
2022-04-01 18:17:42.658 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/album/1/photo/1?photo_id=2&user_id=1', ip: '127.0.0.1', author: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsImV4cCI6MTY0ODg3ODg0NH0.mbEedLMYH2S1uk63LIdUcqIW5Rj5gdgeiVYB8lcG1qg', query: 'photo_id=2&user_id=1', body: '', time: 18ms
2022-04-01 18:18:03.038 | ERROR    | conf.logger:log_request_error:18 - uid: 1, requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/album/1/photo/1?user_id=1', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'user_id=1', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.album.photo_views.PhotoHandler object at 0x7fd669d080d0>
             │       │    └ ['1', '1']
             │       └ <views.album.photo_views.PhotoHandler object at 0x7fd669d080d0>
             └ <bound method PhotoHandler.get of <views.album.photo_views.PhotoHandler object at 0x7fd669d080d0>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/album/photo_views.py", line 40, in get
    if not photo: raise ClientError('图片不存在')
           │            └ <function ClientError at 0x7fd669c41e50>
           └ None

common.exception.SaoException: ('图片不存在', 1007)
2022-04-01 18:18:03.051 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/album/1/photo/1?user_id=1', ip: '127.0.0.1', author: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsImV4cCI6MTY0ODg3ODg0NH0.mbEedLMYH2S1uk63LIdUcqIW5Rj5gdgeiVYB8lcG1qg', query: 'user_id=1', body: '', time: 18ms
2022-04-01 18:19:29.559 | ERROR    | conf.logger:log_request_error:18 - uid: 1, requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/album/1/photo/1?user_id=1', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'user_id=1', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.album.photo_views.PhotoHandler object at 0x7fd669d8d520>
             │       │    └ ['1', '1']
             │       └ <views.album.photo_views.PhotoHandler object at 0x7fd669d8d520>
             └ <bound method PhotoHandler.get of <views.album.photo_views.PhotoHandler object at 0x7fd669d8d520>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/album/photo_views.py", line 40, in get
    if not photo: raise ClientError('图片不存在')
           │            └ <function ClientError at 0x7fd669c41e50>
           └ None

common.exception.SaoException: ('图片不存在', 1007)
2022-04-01 18:19:29.564 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/album/1/photo/1?user_id=1', ip: '127.0.0.1', author: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsImV4cCI6MTY0ODg3ODg0NH0.mbEedLMYH2S1uk63LIdUcqIW5Rj5gdgeiVYB8lcG1qg', query: 'user_id=1', body: '', time: 13ms
2022-04-01 18:19:56.504 | ERROR    | conf.logger:log_request_error:18 - uid: 1, requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/album/1/photo/1?user_id=1', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'user_id=1', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.album.photo_views.PhotoHandler object at 0x7fe3d6bd4fd0>
             │       │    └ ['1', '1']
             │       └ <views.album.photo_views.PhotoHandler object at 0x7fe3d6bd4fd0>
             └ <bound method PhotoHandler.get of <views.album.photo_views.PhotoHandler object at 0x7fe3d6bd4fd0>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/album/photo_views.py", line 40, in get
    if not photo: raise ClientError('图片不存在')
           │            └ <function ClientError at 0x7fe3d6b30e50>
           └ None

common.exception.SaoException: ('图片不存在', 1007)
2022-04-01 18:19:56.517 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/album/1/photo/1?user_id=1', ip: '127.0.0.1', author: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsImV4cCI6MTY0ODg3ODg0NH0.mbEedLMYH2S1uk63LIdUcqIW5Rj5gdgeiVYB8lcG1qg', query: 'user_id=1', body: '', time: 99ms
2022-04-01 18:20:08.220 | ERROR    | conf.logger:log_request_error:18 - uid: 1, requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/v1/album/1/photo/1?user_id=1', version='HTTP/1.1', remote_ip='127.0.0.1'), query: 'user_id=1', body b''
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.album.photo_views.PhotoHandler object at 0x7fa887506040>
             │       │    └ ['1', '1']
             │       └ <views.album.photo_views.PhotoHandler object at 0x7fa887506040>
             └ <bound method PhotoHandler.get of <views.album.photo_views.PhotoHandler object at 0x7fa887506040>>

  File "/Users/qiangchen/Desktop/sesame/sesame-backend/views/album/photo_views.py", line 41, in get
    if not photo: raise ClientError('图片不存在')
           │            └ <function ClientError at 0x7fa887330e50>
           └ None

common.exception.SaoException: ('图片不存在', 1007)
2022-04-01 18:20:08.236 | ERROR    | conf.logger:log_request:30 - status: 500, method: 'GET', uri: '/v1/album/1/photo/1?user_id=1', ip: '127.0.0.1', author: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsImV4cCI6MTY0ODg3ODg0NH0.mbEedLMYH2S1uk63LIdUcqIW5Rj5gdgeiVYB8lcG1qg', query: 'user_id=1', body: '', time: 106ms
